kiosk/urls.py
from django.urls import path

from . import views

app_name = 'kiosk'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
]

sheltertrack/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('kiosk/', include('kiosk.urls')),
    path('admin/', admin.site.urls),
]

kiosk/models.py
from django.db import models
from django.utils import timezone

class Location(models.Model):
    name = models.CharField(max_length=200)
    capacity = models.PositiveIntegerField()
    show_on_dashboard = models.BooleanField(default=True)

    def __str__(self):
        return '{n}'.format(n=self.name)

class Animal(models.Model):
    species = models.CharField(max_length=64)
    name = models.CharField(max_length=200)
    intake_date = models.DateTimeField('intake date')
    exit_date = models.DateTimeField('exit date', default=None, blank=True, null=True)
    location = models.ForeignKey(Location, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return '{i}/{s}/{n}'.format(i=self.id, n=self.name, s=self.species)

    @property
    def is_active(self):
        return (self.intake_date <= timezone.now()) and ((self.exit_date is None) or (self.exit_date > timezone.now()))

class MedicalNote(models.Model):
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    start_date = models.DateTimeField('start date')
    end_date = models.DateTimeField('end date')
    instruction = models.CharField(max_length=1024)
    notes = models.CharField(max_length=1024, default=None, blank=True, null=True)

    def __str__(self):
        return '{n} Note {i}'.format(n=self.animal, i=self.id)

    def is_active(self):
        return (self.start_date <= timezone.now()) and ((self.end_date is None) or (self.end_date > timezone.now()))

"""
Other ideas:
 - Split medical and food notes
 - Allow for food, behavior note input
 - Detailed medical notes
  - FIV/FeLV status
  - Microchip Number
  - Fecal results
  - Rabies vaccine info (+ date?)
  - Other vaccine info (name + date?)
"""

kiosk/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse
from django.utils import timezone

from .models import Animal, MedicalNote, Location


class IndexView(generic.ListView):
    template_name = 'kiosk/index.html'
    context_object_name = 'animal_list'

    def get_queryset(self):
        return Animal.objects.filter(intake_date__lte=timezone.now())

class DetailView(generic.DetailView):
    model = Animal
    template_name = 'kiosk/detail.html'

class DashboardView(generic.ListView):
    template_name = 'kiosk/dashboard.html'
    context_object_name = 'dataset'

    def get_queryset(self):
        # There may be a better way to aggregate this information, but this seems to work.
        dataset = {'locations':{}, 'count':0}
        for loc in Location.objects.filter(show_on_dashboard__exact=True):
            dataset['locations'][loc] = {}
            qs = Animal.objects.filter(location__id__exact=loc.id, intake_date__lte=timezone.now(), exit_date__gte=timezone.now()) | Animal.objects.filter(location__id__exact=loc.id, intake_date__lte=timezone.now(), exit_date__isnull=True)
            for animal in qs:
                dataset['locations'][loc][animal] = []
                for note in animal.medicalnote_set.all():
                    if note.is_active():
                        dataset['locations'][loc][animal].append(note)
            # For each location, get a list of active animals in that location
            dataset['count'] += len(dataset['locations'][loc])

        return dataset

kiosk/templates/kiosk/dashboard.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'kiosk/style.css' %}">

<h1 style="text-align: center;">
    Shelter Name
    <span style="float: left;">
        {{ dataset.count }}
    </span>
</h1>

{% for k, v in dataset.locations.items %}
<h2>{{ k.name }}</h2>
<div class="flex-container">
    {% for animal, notes in v.items %}
    <div class="flex-item">
        <h3 style="text-align: center; vertical-align: top;"><a href="{% url 'kiosk:detail' animal.id %}">{{ animal.name }}</a></h3>
        <div class="medicalnotes">
        <table>
            {% for note in notes %}
            {% if forloop.first %}
            <tr>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Instruction</th>
                <th>Notes</th>
            </tr>
            {% endif %}
            <tr>
                <td>{{ note.start_date }}</td>
                <td>{{ note.end_date }}</td>
                <td>{{ note.instruction }}</td>
                <td>{{ note.notes }}</td>
            </tr>
            {% endfor %}
        </table>
        </div>
    </div>
    {% endfor %}
</div>
{% endfor %}

kiosk/templates/kiosk/detail.html
<h1>{{ animal.name }} ({{ animal.species }})</h1>
{% if animal.is_active == True %}
<p>Active since {{ animal.intake_date }}</p>
{% else %}
<p>Inactive since {{ animal.exit_date }}</p>
{% endif %}

<h2>Location</h2>
<p>{{ animal.location }}</p>

<h2> Medical Notes</h2>
{% if animal.medicalnote_set.count != 0 %}
<table>
    <tr>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Instruction</th>
        <th>Notes</th>
    </tr>
{% for note in animal.medicalnote_set.all %}
    <tr>
        <td>{{ note.start_date }}</td>
        <td>{{ note.end_date }}</td>
        <td>{{ note.instruction }}</td>
        <td>{{ note.notes }}</td>
    </tr>
{% endfor %}
</table>
{% endif %}

kiosk/templates/kiosk/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'kiosk/style.css' %}">
{% if animal_list %}
    <ul>
    {% for animal in animal_list %}
    <li><a href="{% url 'kiosk:detail' animal.id %}">{{ animal.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No animals are available.</p>
{% endif %}